name: deployment-flow
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.10

      - name: Install Setuptools
        run: pip3 install -U pip setuptools

      - name: Upgrade PIP
        run: pip install --upgrade pip
        